// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions
{
  static FirebaseOptions get currentPlatform
  {
    if (kIsWeb)
    {
      return web;
    }
    switch (defaultTargetPlatform)
    {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOaR5CnyHQMm8hxt-aFMvS9v5MSp4VznA',
    appId: '1:720021806724:web:9a88cc4bd1d3c0601eecd1',
    messagingSenderId: '720021806724',
    projectId: 'flutter-messenger-935da',
    authDomain: 'flutter-messenger-935da.firebaseapp.com',
    storageBucket: 'flutter-messenger-935da.appspot.com',
    measurementId: 'G-RSEM8D3KS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBadoEDQLfbBeO6ayMUJ4RAdpBUZsrXQ40',
    appId: '1:720021806724:android:559611b4665465441eecd1',
    messagingSenderId: '720021806724',
    projectId: 'flutter-messenger-935da',
    storageBucket: 'flutter-messenger-935da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI0uM_iMZ3rVlYXRvtbpJeJ2VnKKooT00',
    appId: '1:720021806724:ios:9be287999fa27e331eecd1',
    messagingSenderId: '720021806724',
    projectId: 'flutter-messenger-935da',
    storageBucket: 'flutter-messenger-935da.appspot.com',
    iosClientId: '720021806724-ornmnd7f2s4nnd2uhgd93pkkhoegbf5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI0uM_iMZ3rVlYXRvtbpJeJ2VnKKooT00',
    appId: '1:720021806724:ios:9be287999fa27e331eecd1',
    messagingSenderId: '720021806724',
    projectId: 'flutter-messenger-935da',
    storageBucket: 'flutter-messenger-935da.appspot.com',
    iosClientId: '720021806724-ornmnd7f2s4nnd2uhgd93pkkhoegbf5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermessenger',
  );
}
